version: "3.5"

services:
  backend:
    container_name: backend
    build: .
    command: uwsgi --socket=:9000 --module=honest_sherpa.wsgi:application --py-autoreload=1
    volumes:
      - .:/code
    networks: 
      - webnet
  
  nginx:
    image: nginx:1.15.0
    depends_on:
      - backend
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    networks:
      - webnet
    ports:
      - "80:80"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks: 
  webnet:
